CREATE TABLE IF NOT EXISTS poll (
  id INT PRIMARY KEY AUTO_INCREMENT,
  question VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS poll_option (
  id INT PRIMARY KEY AUTO_INCREMENT,
  poll_id INT NOT NULL,
  label VARCHAR(100) NOT NULL,
  CONSTRAINT fk_poll_option_poll
    FOREIGN KEY (poll_id) REFERENCES poll(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS vote (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  poll_id INT NOT NULL,
  option_id INT NOT NULL,
  username VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vote_option
    FOREIGN KEY (option_id) REFERENCES poll_option(id) ON DELETE CASCADE
);
